const FETCH_WEATHER = "FETCH_WEATHER";
const GET_USER_LOCATIONS = "GET_USER_LOCATIONS";
const SET_USER_LOCATIONS = "SET_USER_LOCATIONS";
const SYNC_UPDATE_LOCATIONS = "SYNC_UPDATE_LOCATIONS";

export {
    FETCH_WEATHER,
    GET_USER_LOCATIONS,
    SET_USER_LOCATIONS,
    SYNC_UPDATE_LOCATIONS,
};
