const ADD_LOCATION = "ADD_LOCATION";
const REMOVE_LOCATION = "REMOVE_LOCATION";
const UPDATE_LOCATIONS_ORDER = "UPDATE_LOCATIONS_ORDER";
const UPDATE_LOCATION_WEATHER = "UPDATE_LOCATION_WEATHER";

export {
    ADD_LOCATION,
    REMOVE_LOCATION,
    UPDATE_LOCATIONS_ORDER,
    UPDATE_LOCATION_WEATHER,
};
